### PR TITLE
Use suggestions API for `no-only-test` and `no-skip-test`

### PR DESCRIPTION
**Pull request by edbrannin**
Closes https://github.com/avajs/eslint-plugin-ava/pull/324
https://github.com/avajs/eslint-plugin-ava/issues/281#issuecomment-587137623

### CODE REVIEW

**Comment by edbrannin** [comment]
@sindresorhus Integration tests are failing in the same way as they did in #324.  Was the build already broken?

**Comment by sindresorhus** [comment]
You need to update the rule docs and the readme.

**Comment by edbrannin** [comment]
Whoops, thanks!  I'll fix.

...actually, I checked the eslint code rules, the [only]() [two]() that support the `suggest:` API don't say anything about that or autofix in the docs.

Should I just drop references to Fixable for these rules, or would you prefer some other language?

[only]: https://eslint.org/docs/rules/no-useless-escape
[two]: https://eslint.org/docs/rules/no-unsafe-negation

**Comment by sindresorhus** [comment]
> Should I just drop references to Fixable for these rules, or would you prefer some other language?

Drop

**Comment by edbrannin** [comment]
Done

(oh yay, the integration test is working now too!)

**Comment by edbrannin** [comment]
Thanks!

If you don't mind my asking, any idea when this might be released?  I'm very much looking forward to updating this plugin on my services.

**Comment by sindresorhus** [comment]
It was released half an hour ago.

**Comment by edbrannin** [comment]
Oh, double-thanks then!  Keep up the good work!

**Pull request merged**
