### PR TITLE
Add auto-fix of misspelled `falsey` to `falsy`

### LINKED ISSUE #190: Auto-fix `falsey` to `falsy` in the `use-t-well` rule
Context: https://github.com/avajs/ava/issues/1807

### PR DESCRIPTION
**Pull request by GMartigny**
fix #190

### CODE REVIEW

**Comment by GMartigny** [comment]
Hi,

It feels like this should be in a separate rule as this is the only error "fixable".

The error message could be better, but I've gone with simplicity.

 - [ ] Still need to update the documentation

**Comment by novemberborn** [comment]
Thanks for all your PRs @GMartigny!

> It feels like this should be in a separate rule as this is the only error "fixable".

@sindresorhus?

**Comment by sindresorhus** [comment]
You need to update the readme and rule docs to indicate it's fixable.

**Comment by sindresorhus** [comment]
> It feels like this should be in a separate rule as this is the only error "fixable".

I think it's fine to keep it in this rule.

**Comment by sindresorhus** [comment]
> It feels like this should be in a separate rule as this is the only error "fixable".

https://github.com/avajs/eslint-plugin-ava/blob/ab64fde19092318aa6b7726e81bb1808d866fdba/test/use-t-well.js#L115-L116 could potentially be fixable too.

**Comment by GMartigny** [comment]
> You need to update the readme and rule docs to indicate it's fixable.

I updated the readme.md, but other fixable rules (no-only-test, no-skip-test) doc don't mention they are fixable.
What could be added to better communicate the fixable state ?

**Comment by sindresorhus** [comment]
> I updated the readme.md, but other fixable rules (no-only-test, no-skip-test) doc don't mention they are fixable.

That's just an oversight. Would you be willing to fix those in a separate PR?

**Comment by sindresorhus** [comment]
> What could be added to better communicate the fixable state ?

Explain what's fixable in the rule docs. Example: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prevent-abbreviations.md#prevent-abbreviations

**Comment by sindresorhus** [comment]
> Explain what's fixable in the rule docs. Example: sindresorhus/eslint-plugin-unicorn:docs/rules/prevent-abbreviations.md@master#prevent-abbreviations 

@GMartigny Can you add this to the rule documentation for this rule so this PR can be merged?

**Pull request merged**
