### PR TITLE
Add tests to enforce some rule guidelines

### LINKED ISSUE #242: Add general rule tests
Like: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/package.js Can probably just borrow those directly.

### PR DESCRIPTION
**Pull request by gurrrung**
Fixes #242

### CODE REVIEW

**Comment by GMartigny** [comment]
Looks good to me

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by gurrrung** [comment]
@sindresorhus done.

**Comment by sindresorhus** [comment]
You didn't resolve the merge conflict correctly. Look at the diff. Many unrelated changes.

**Comment by gurrrung** [comment]
@sindresorhus good to go.

**Comment by sindresorhus** [comment]
You still have unrelated changes. Please look at the diff carefully.

**Comment by gurrrung** [comment]
Hey, I double checked and couldn't find any unrelated changes, can you point to it, please.

**Comment by gurrrung** [comment]
@sindresorhus good to go?

**Comment by sindresorhus** [comment]
Yup. Thank you :)

**Pull request merged**
