### PR TITLE
Enforce strict mode

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by sindresorhus** [comment]
CI is failing. Looks unrelated but weird that it fails only here and not the main branch.

**Comment by fisker** [comment]
Disabled that rule and opened an issue to track #342

**Comment by fisker** [comment]
Maybe because it's not strict, `eslint-plugin-eslint-plugin` can't locate something?

**Comment by sindresorhus** [comment]
Seems so

**Pull request merged**
