### PR TITLE
Improve tests feedback, linked to #104

### PR DESCRIPTION
**Pull request by jfmengels**
This is related to #104, and an attempt to improve the RuleTester's feedback. By default, it uses Mocha's `describe` and `it` to create rules, but it they are not defined, it uses the functions [here](https://github.com/eslint/eslint/blob/master/lib%2Ftesters%2Frule-tester.js#L436-L452).

I've managed to override the RuleTester test creation a bit to use AVA's `test` rather than Mocha's `it`, and here are the results:

### When run with Mocha
image

### When run with AVA (with `--verbose`)
image

### When run with AVA and `tap-mocha-reporter`

image

The odd `test.xxx(t => {})` kind of everywhere are the second part of the title (since it takes as title the code, and the code has a `\n` in the middle). If we remove the `\n`, it gets much clearer
image

Please check out [`eslint-ava-rule-tester`](https://github.com/jfmengels/eslint-ava-rule-tester), which exports a modified RuleTester. I'm up for modifying the name, but it's already published (could not make it all work with `npm link`), which contains the same code that you can see in `test/helpers/ava-rule-tester.js` (I kept it ll so that you guys could easily see what I did here).

Let me know what you guys think.

PS: Obviously this is just a draft, I haven't migrated all the tests and have even left an error so that you can see the error feedback more easily.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice! Looks so much better now :)

**Comment by sindresorhus** [comment]
Maybe we should do a PR to ESLint adding a hook to their rule checker so any test framework could easily hook into it?

**Comment by jfmengels** [comment]
> Nice! Looks so much better now :)

Yeah!

> Maybe we should do a PR to ESLint adding a hook to their rule checker so any test framework could easily hook into it?

Sure. By their contribution guidelines, we should first create an issue though. Not sure I see what the hook should look like though?

**Comment by jfmengels** [comment]
By the way: Found this comment https://github.com/eslint/eslint/issues/5040#issuecomment-182693246, where they talk about eventually using AVA under the hood for RuleTester.

**Comment by jfmengels** [comment]
Created an issue in ESLint about this https://github.com/eslint/eslint/issues/6227

**Comment by jfmengels** [comment]
Now that we know that ESLint considers this okay and `describe` and `it` as part of their API (meaning it will be enforced by semver), shall I go ahead with finishing this? If so, I'll go ahead and do `eslint-plugin-xo` too (and my own plugins).

**Comment by jfmengels** [comment]
### Before
image

### After
image

Biggest number of test additions you'll ever see in one commit :D

**Comment by jfmengels** [comment]
Hmm, looking into the tests a bit later today. Stay tuned.

**Comment by sindresorhus** [comment]
> shall I go ahead with finishing this?

Let's do it! :D

**Comment by jfmengels** [comment]
There you go :)

**Comment by sindresorhus** [comment]
Yay! So much better output :)

leo-excited

**Comment by jfmengels** [comment]
:)

Will do a PR for xo soon-ish.

**Comment by jfmengels** [comment]
PS: https://github.com/eslint/eslint/pull/6331, if you have comments to improve this ;)

**Pull request merged**
