### PR TITLE
Support extensions, files and helpers in `no-ignored-test-files` and `no-import-test-files` rules

### LINKED ISSUE #252: `no-ignored-test-files` does not work when test files are manually transpiled
If I understood correctly, the new `no-ignored-test-files` uses the Ava configuration to figure out where test files are. 

However I transpile my tests with Babel from `test/**` to `build/test/**`. I explicitly use `{ babel: false, compileEnhancements: false }`. 

Which means `test/**` are linted, but `build/test/**` are run by Ava. Under those circumstances, `no-ignored-test-files` assumption is wrong and reports all my test files with `error  AVA ignores this file`.

### PR DESCRIPTION
**Pull request by novemberborn**
Fixes #252.

Depends on https://github.com/avajs/ava/pull/2150.

### CODE REVIEW

**Comment by novemberborn** [comment]
@ehmicky could you give this a try? You'll have to install this AVA PR as well: https://github.com/avajs/ava/pull/2150

Note that I haven't actually tried this yet, but I think it might work 😉

**Comment by ehmicky** [comment]
Thanks for this PR. 

This does not seem to work for me:

In `.eslintrc.yml`:

```yml
  ava/no-ignored-test-files:
  - 2
  - files: [test/**/*.js]
```

`ava.config.js`:

```js
export default {
  // Files are transpiled from `test/` to `build/test/`
  files: ['build/test/**/*.js'],
  helpers: ['build/test/helpers/**/*.js'],
  sources: ['build/**/*.js'],
  babel: false,
  compileEnhancements: false,
}
```

Then:

```
$ eslint test/main.js

/home/code/example/test/main.js
  1:1  error  AVA ignores this file  ava/no-ignored-test-files

✖ 1 problem (1 error, 0 warnings)
```

**Comment by novemberborn** [comment]
> This does not seem to work for me:

Yea silly mistake on the AVA side. I've force-pushed https://github.com/avajs/ava/pull/2150 — could you give this another go?

**Comment by ehmicky** [comment]
Yes it works now, thanks!

**Pull request merged**
