### PR TITLE
update no-unknown-modifier rules, resolve #107

### LINKED ISSUE #107: Update no-unknown-modifiers rule to accept failing and always modifier
sindresorhus/ava#831 will add `failing` modifier.

The modifier `always` was added in sindresorhus/ava#806

### PR DESCRIPTION
**Pull request by cgcgbcbc**
add always, failing modifier. resolve #107

### CODE REVIEW

**Comment by jamestalmage** [comment]
#102 already covers `always` (I just merged it).

You need to rebase, and drop the `always` related stuff.

**Comment by cgcgbcbc** [comment]
@jamestalmage rebased

**Comment by jamestalmage** [comment]
LGTM!

We will wait for sindresorhus/ava#831 to land before merging.

Thanks @cgcgbcbc!

**Comment by jfmengels** [comment]
LGTM, thanks @cgcgbcbc :)

**Comment by jamestalmage** [comment]
Somebody should write a bot that would notify you in this thread, when the thread you are watching gets closed / merged.

Would have been better to merge this right after #831 landed so we weren't risking making the contributor rebase (he didn't end up having to, which is good, but it would be annoying if he did because we just forgot this was sitting here).

**Pull request merged**
